import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { defineConfig, type Plugin } from 'vite';

/**
 * Emits a service worker that precaches the exact build output.
 *
 * Doing it after the bundle means the hashed asset names are known, so the game
 * is genuinely playable offline on the first reload rather than only warming a
 * runtime cache.
 */
function offlinePlugin(outDir = 'dist'): Plugin {
  return {
    name: 'facedown-offline',
    apply: 'build',
    closeBundle() {
      const files: string[] = [];
      const walk = (dir: string): void => {
        for (const entry of readdirSync(dir)) {
          const full = join(dir, entry);
          if (statSync(full).isDirectory()) walk(full);
          else files.push('./' + relative(outDir, full).split('\\').join('/'));
        }
      };
      walk(outDir);
      const assets = files.filter((f) => f !== './sw.js');
      const hash = createHash('sha1')
        .update(assets.map((f) => f + statSync(join(outDir, f)).size).join('|'))
        .digest('hex')
        .slice(0, 10);

      const sw = `/* Generated by vite. Do not edit. */
const CACHE = 'facedown-${hash}';
const ASSETS = ${JSON.stringify(assets, null, 0)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(
    caches.match(req).then((hit) => {
      if (hit) return hit;
      return fetch(req)
        .then((res) => {
          if (res.ok && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() => caches.match('./index.html'));
    }),
  );
});
`;
      writeFileSync(join(outDir, 'sw.js'), sw);
      const bytes = assets.reduce((n, f) => n + statSync(join(outDir, f)).size, 0);
      readFileSync(join(outDir, 'index.html'));
      this.warn?.(`offline cache: ${assets.length} files, ${(bytes / 1024).toFixed(0)} kB`);
    },
  };
}

/**
 * `FACEDOWN_STANDALONE=1` produces a build meant to be inlined into a single
 * HTML file: no service worker and no Web Worker, so it runs anywhere a page
 * can, at the cost of solving on the main thread.
 */
const standalone = process.env.FACEDOWN_STANDALONE === '1';

export default defineConfig({
  base: './',
  define: { __STANDALONE__: JSON.stringify(standalone) },
  plugins: standalone ? [] : [offlinePlugin()],
  build: {
    target: 'es2020',
    outDir: 'dist',
    assetsInlineLimit: 8192,
    cssCodeSplit: false,
    sourcemap: false,
    // One chunk, so the standalone build can be a single inline <script>.
    rollupOptions: standalone ? { output: { inlineDynamicImports: true } } : {},
  },
  server: { host: true, port: 5173 },
  test: {
    environment: 'node',
    include: ['tests/**/*.test.ts'],
  },
} as any);
